	location ~ ^/track/[a-f0-9-]+/[A-Za-z0-9_]+/.*$ {
		if ($request_method = GET) {
			access_log /var/log/nginx/tracking.octoprint.org/tracking.log tracking;
			return 204;
		}

		if ($request_method = POST) {
			access_log /var/log/nginx/tracking.octoprint.org/tracking.log tracking;
			proxy_pass $scheme://127.0.0.1/logsink;
			break;
		}

		return 405;
	}

	location /logsink {
		return 204;
	}
