input {
    file {
        path => [ "/var/log/nginx/tracking.octoprint.org/tracking.log" ]
        type => "nginx-access"
        start_position => "beginning"
    }
}

filter {
    grok {
        match => { "message" => '%{IPORHOST:clientip} \[%{HTTPDATE:timestamp}\] "%{WORD:verb} %{URIPATHPARAM:request} HTTP/%{NUMBER}" %{INT:response} %{INT} %{QS:request_body} "OctoPrint/(?<octoprint_version>[^"]+)"' }
        overwrite => [ "message" ]
    }
    mutate {
        convert => ["response", "integer"]
    }
    geoip {
        source => "clientip"
        target => "geoip"
    }
#    fingerprint {
#        sources => ["clientip", "timestamp", "request", "request_body"]
#        target => "@fingerprint"
#        method => "SHA512"
#    }

    mutate {
        remove_field => [ "clientip", "[geoip][ip]", "message" ]
    }
    date {
        match => [ "timestamp" , "dd/MMM/YYYY:HH:mm:ss Z" ]
        remove_field => [ "timestamp" ]
    }

    if [verb] == "GET" {
        grok {
            match => [ "request" , "/track/%{UUID:uuid}/(?<event>[^/]*)/(?<payload_args>[^?]*)(\?%{GREEDYDATA:payload_query})?" ]
        }
    }

    if [verb] == "POST" {
        grok {
            match => [ "request" , "/track/%{UUID:uuid}/(?<event>[^/]*)/(?<payload_args>[^?]*)" ]
        }
        grok {
            match => [ "request_body" , '"%{GREEDYDATA:payload_query}"' ]
        }
    }

    kv {
        source => "payload_query"
        field_split => "&?"
        target => "payload"
        transform_key => "lowercase"
        remove_field => "payload_query"
        include_keys => ["octoprint_uptime", "printer_state", "version", "os", "bits",
                         "python", "pip", "cores", "freq", "ram", 
                         "pi_model", "octopi_version", "plugin", 
                         "plugin_version", "target", "from_version", 
                         "to_version", "throttled_now", 
                         "throttled_past", "throttled_mask", 
                         "throttled_voltage_now", "throttled_voltage_past", 
                         "throttled_overheat_now", "throttled_overheat_past", 
                         "commerror_text", "origin", "file", "elapsed", 
                         "reason", "firmware_name", "printer_state", "printer_port",
                         "printer_baudrate", "printer_safety_warning_type", 
                         "printer_safety_check_name", "plugins", "slicer",
                         "browser_name", "browser_version", "os_name", "os_version"]
    }
    urldecode {
        field => "payload"
    }
    mutate {
        copy => { "[payload][plugins]" => "[payload][plugins_and_version]" }
    }
    mutate {
        convert => ["[payload][elapsed]", "integer"]
        convert => ["[payload][freq]", "float"]
        convert => ["[payload][cores]", "integer"]
        convert => ["[payload][ram]", "integer"]
        convert => ["[payload][bits]", "integer"]
        convert => ["[payload][printer_baudrate]", "integer"]
        convert => ["[payload][throttled_mask]", "integer"]
        convert => ["[payload][octoprint_uptime]", "integer"]
        split => { "[payload][plugins_and_version]" => "," }
        gsub => ["[payload][plugins]", ':[^,]*', ""]
        split => { "[payload][plugins]" => "," }
    }
    if [event] == "webui_load" {
        mutate {
            add_field => { "browser_name_and_version" => "%{[payload][browser_name]}/%{[payload][browser_version]}" }
            add_field => { "browser_os_and_version" => "%{[payload][os_name]}/%{[payload][os_version]}" }
        }
    }
    grok {
        match => [ "octoprint_version" , "(?<octoprint_public_version>(?<octoprint_base_version>\d+\.\d+\.\d+(?:a|b|rc\d+)?)(?:\.[^+]+)?)(?:\+g(?<octoprint_local_version>[^\.]*))?(?:\.(?<octoprint_dirty_version>dirty))?" ]
    }
}

output {
   elasticsearch {
       hosts => ["localhost:9200"]
       index => "tracking-live-%{+YYYY.MM.dd}"
       #document_id => "@fingerprint"
   }
}

